# -*- coding: utf-8 -*-
"""StatsLab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14AzbfMBafm5OwO_ZPHNPkNyQ9r6_0Gek
"""

import requests
import pandas
import numpy as np
import matplotlib.pyplot as plt

url = "https://richardson.byu.edu/220/ds_salary.csv"
filename = "ds_salary.csv"

chart = pandas.read_csv(url)
chart.to_csv(filename)

display(chart)

plt.figure(figsize=(8,4))
plt.hist(chart["salary_in_usd"], bins=17 , edgecolor='black')
plt.title(f'Histogram of Salary')
plt.xlabel("salary")
plt.ylabel('# of data scientists')
plt.show()

"""#**General Salary Data:**

Based off the histogram, the mean salary in USD for data scientists is around 115601. On average, each person's salary deviates from the mean around 70546 USD. The mediam salary between all sata scientists is 105000. The histogram is right skewed indicating that most data scientists will fall on the lower end of the pay range with few exceding the traditional salary.
"""

mean_value = np.mean(chart["salary_in_usd"])
median_value = np.median(chart["salary_in_usd"])
std_deviation = np.std(chart["salary_in_usd"])
variance = np.var(chart["salary_in_usd"])

# Display the results
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_deviation}")
print(f"Variance: {variance}")

plt.boxplot([chart[chart['experience_level'] == 'EN']['salary_in_usd'],
             chart[chart['experience_level'] == 'MI']['salary_in_usd'],
             chart[chart['experience_level'] == 'SE']['salary_in_usd'],
             chart[chart['experience_level'] == 'EX']['salary_in_usd']],
            labels=['EN', 'MI', 'SE', 'EX'])
plt.show()

"""#**Effect of Experience on Salary:**

It is clear that the EX level receives a significantly higher pay rate in comparison to the EN level. However when the average is compared to the MI and SE levels the SE middle range is within the middle to lower range of the EX indicating that more experience doesn't always indicate higher pay. The EX level does however have the higher outlier meaning that the higher paid data scientist would have EX experience. The EN level has the most consistent pay rate compared to the other levels with very little fluctuation and outliers.

"""

for exp_level in ['EN', 'MI', 'SE', 'EX']:
    salaries = chart[chart['experience_level'] == exp_level]['salary_in_usd']
    print(f"Experience Level: {exp_level}")
    print(f"Five-Number Summary: {salaries.describe()}")
    print(f"Mean: {salaries.mean()}")
    print(f"Median: {salaries.median()}")
    print(f"Standard Deviation: {salaries.std()}")
    print("-" * 20)

plt.boxplot([chart[chart['company_size'] == 'S']['salary_in_usd'],
             chart[chart['company_size'] == 'M']['salary_in_usd'],
             chart[chart['company_size'] == 'L']['salary_in_usd']],
            labels=['S', 'M', 'L'])
plt.xlabel("Company Size")
plt.ylabel("Salary")
plt.title("Salary Distribution by Company Size")
plt.show()

"""#**Effect of Company Size on Salary:**

The box plot shows that data scientists have higher salaries on average in middle to large size commpanies compared to smaller companies. The data shows that the larger the company is, the higher the mean, median and highest possible salary achievable is. Based on the data, a small company has an average salary of 79817.83, a median company on average pays 118350, and for a large company the average is 126090.01. In a large company especially, there are more outliers who make a significant amount of money, max being 600000, compared to Mid and smaller sized companies whose max is 416000, and 450000 respectively.
"""

for exp_level in ['S', 'M', 'L']:
    salaries = chart[chart['company_size'] == exp_level]['salary_in_usd']
    print(f"Experience Level: {exp_level}")
    print(f"Five-Number Summary: {salaries.describe()}")
    print(f"Mean: {salaries.mean()}")
    print(f"Median: {salaries.median()}")
    print(f"Standard Deviation: {salaries.std()}")
    print("-" * 20)

# Create a list to store salaries for each job category
salaries = []

# Extract salaries for each job category
for job_type in ['Engineer', 'Scientist', 'Analyst']:
  salaries.append(chart[chart['job_title'].str.contains(job_type, case=False)]['salary_in_usd'])

# Create the box plot
plt.boxplot(salaries, labels=['Engineer', 'Scientist', 'Analyst'])
plt.xlabel("Job Title")
plt.ylabel("Salary (USD)")
plt.title("Salary Comparison for Different Job Titles")
plt.show()

"""#**Job Title Analysis:**
It is made clear by the box-plot that key indicators in job title such as Engineer, Scientist, and Analyst have the smallest relationship witht the salary. The Engineer title clearly represents the group with the highest average pay but only by small margins. The Engineer title also has the higher outlier indicating that the highest paid data workers will be engineers. The scientist category has a group of outliers indicating that while average salary is very similar to the Engineer title there is a small group of Scientists consitantly paid more than the rest. Anaylsts have the smallest spread and average indicating that they recieve the most consistantly lower salaries.

"""

import pandas as pd

# Create a pivot table and find mean of salary
grouped_data = chart.groupby(['job_title', 'company_size'])['salary'].mean().reset_index()

pivot_table = pd.pivot_table(grouped_data, values='salary', index='job_title', columns='company_size')

# Print the pivot table
print(pivot_table.round(1))

"""#**Conclusion:**
Overall it is clear that there are many relationships that can impact salary. This includes experience, company, job title, and others. It is not necessarily clear in the data whether or not the title truly impacts the pay rate or if it is just indicative of a lower paying field. Experience and Company size both have large impacts on salary.

Mean salary between all types of data scientists is around 115,601. In this field, it seems like the more experienced you are, the more money you will make. In larger companies, the mean salary is around 126,090 compared to smaller companies whose average salary is 118,350. In terms of salary comparison with different job titles, engineers and scientists make more money in general than analysts, but the outliers for salary in mean are more extreme compared to both scientists and analysts.
"""